name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Publish Windows
      run: dotnet publish -c Release -r win-x64 -o win --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true
    - name: Publish MacOS
      run: dotnet publish -c Release -r osx-x64 -o linux --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true
    - name: Publish Linux
      run: dotnet publish -c Release -r linux-x64 -o osx --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true
    - name: Rename Artifacts
      run: |
        mkdir dist
        mv win/JsonTools.exe dist/JsonTools.exe
        mv linux/JsonTools dist/JsonTools.linux.dll
        mv osx/JsonTools dist/JsonTools.osx.dll
    - name: Publish Artifacts
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        title: "Latest Build"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        files: |
          dist/JsonTools.exe
          dist/JsonTools.linux.dll
          dist/JsonTools.osx.dll

            
